spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_service?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: da1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8283
